/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddClassesModal: typeof import('./src/components/modals/AddClassesModal.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    ChildSpecialistInfoModal: typeof import('./src/components/modals/ChildSpecialistInfoModal.vue')['default']
    ClassesInfoModal: typeof import('./src/components/modals/ClassesInfoModal.vue')['default']
    ClassesModal: typeof import('./src/components/modals/ClassesModal.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DatePickerResponsive: typeof import('./src/components/DatePickerResponsive.vue')['default']
    DateRangePickerModal: typeof import('./src/components/modals/DateRangePickerModal.vue')['default']
    DeleteClassConfirmationModal: typeof import('./src/components/modals/DeleteClassConfirmationModal.vue')['default']
    GroupDetailsModal: typeof import('./src/components/modals/GroupDetailsModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IncompleteBookingToast: typeof import('./src/components/toasts/IncompleteBookingToast.vue')['default']
    PackageInfoBox: typeof import('./src/components/PackageInfoBox.vue')['default']
    ParticipantAccordion: typeof import('./src/components/ParticipantAccordion.vue')['default']
    ParticipantCard: typeof import('./src/components/ParticipantCard.vue')['default']
    ParticipantData: typeof import('./src/components/ParticipantData.vue')['default']
    PopupSmall: typeof import('./src/components/modals/PopupSmall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedParticipantClasses: typeof import('./src/components/SelectedParticipantClasses.vue')['default']
    StayDateDisplay: typeof import('./src/components/StayDateDisplay.vue')['default']
    StepOne: typeof import('./src/components/StepOne.vue')['default']
    StepThree: typeof import('./src/components/StepThree.vue')['default']
    StepTwo: typeof import('./src/components/StepTwo.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    TimerToast: typeof import('./src/components/toasts/TimerToast.vue')['default']
    Toast: typeof import('./src/components/toasts/Toast.vue')['default']
  }
}
